services:
    training_first_theme.layout.data_provider.weather:
        class: 'Training\Bundle\FirstThemeBundle\Layout\DataProvider\WeatherDataProvider'
        tags:
            - { name: layout.data_provider, alias: training_first_theme_weather }

#    oro_customer.provider.frontend_customer_user_registration_form: <---old line
    training_first_theme.layout.frontend_customer_user_registration_form:
        class: 'EDI\Bridge\DonationApplicationFrontendBundle\Layout\DataProvider\DonationApplicationFrontendCustomerUserRegistrationFormProvider'
        public: true
        arguments:
            - "@form.factory"
            - "@oro_config.manager"
            - "@oro_website.manager"
            - "@doctrine"
            - '@router'
        tags:
    #        - { name: layout.data_provider, alias: oro_customer_frontend_customer_user_register } <-- original line - I hope this works!
            - { name: layout.data_provider, alias: edi_oro_customer_frontend_customer_user_register }