features:
  enable_donation_application:
    label: edi.donation_application_bridge.system_configuration.fields.emb_applications.label
    description: edi.donation_application_bridge.system_configuration.fields.emb_applications.tooltip
    toggle: edi.donation_application_bridge.enable_donation_application
    routes:
      - 'edi_donation_application_bridge_donation_page'
